Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torch==1.9.0+cu111 in /home/16amf8/anaconda3/lib/python3.8/site-packages (1.9.0+cu111)
Requirement already satisfied: torchvision==0.10.0+cu111 in /home/16amf8/anaconda3/lib/python3.8/site-packages (0.10.0+cu111)
Requirement already satisfied: torchaudio==0.9.0 in /home/16amf8/anaconda3/lib/python3.8/site-packages (0.9.0)
Requirement already satisfied: typing-extensions in /home/16amf8/anaconda3/lib/python3.8/site-packages (from torch==1.9.0+cu111) (3.7.4.3)
Requirement already satisfied: numpy in /home/16amf8/anaconda3/lib/python3.8/site-packages (from torchvision==0.10.0+cu111) (1.19.2)
Requirement already satisfied: pillow>=5.3.0 in /home/16amf8/anaconda3/lib/python3.8/site-packages (from torchvision==0.10.0+cu111) (8.0.1)
/home/16amf8/anaconda3/lib/python3.8/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
  0%|          | 0/4804 [00:00<?, ?it/s]/home/16amf8/crowd_counting/dataset.py:66: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  gt_file = h5py.File(gt_path)
=> no checkpoint found at '/home/16amf8/data/work_dirs/crowd_counting_UCF-QNRF/UCF-QNRF, cell256, csrnet/checkpoint.pth.tar'
Traceback (most recent call last):
  File "train.py", line 392, in <module>
    main() 
  File "train.py", line 388, in main
    train(args, model, optimizer, train_list, val_list, train_list_depth, val_list_depth, tb_writer, CUDA) 
  File "train.py", line 87, in train
    for bi, (img_big, target_big, img_big_depth) in pbar:  # batch ----------
  File "/home/16amf8/anaconda3/lib/python3.8/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/16amf8/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/16amf8/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/16amf8/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/16amf8/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/16amf8/crowd_counting/dataset.py", line 46, in __getitem__
    img, target, img_depth = load_data(img_path, img_depth_path, self.train, depth=self.depth)
  File "/home/16amf8/crowd_counting/dataset.py", line 67, in load_data
    target = np.asarray(gt_file['density'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/16amf8/anaconda3/lib/python3.8/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'density' doesn't exist)"
